### ISSUE TITLE
Add ToJSON instances that form an isomorphism with FromJSON

### ISSUE THREAD

**Issue by bitemyapp** [himura/twitter-types#14]
This is terribly inconvenient and prevents me doing something as simple as serializing the data into JSON that will "just work" with the library.

**Comment by glasserc** [comment]
I think this can be closed, right?

**Comment by bitemyapp** [comment]
@glasserc I see some ToJSON instances, but no idea the extent of the coverage.

I'll close it for now and re-open if it I bump into problems.

Cheers :)
