### ISSUE TITLE
test case: case_parseErrorMsg: [Failed] with aeson-0.11

### ISSUE THREAD

**Issue by juhp** [himura/twitter-types#38]
We are in the process of moving Stackage Nightly to aeson-0.11.

I see one test failure in the Stackage Nightly build when rebuilding with aeson-0.11:

```
  case_parseErrorMsg: [Failed]
expected: "Not authorized"
 but got: "Error in $: Not authorized"
```

**Comment by himura** [comment]
Thank you for reporting it.

It is caused by the breaking change in `parseEither`, but it only affects test codes. 

I've released a fixed version (0.7.2.1). Please let me know if this is still happening.
